services:
  cloud-1:
    image: cloud-1:dev
    build:
      context: .
    container_name: cloud-1
    env_file:
      - .env
    environment:
      m_TERRAFORM_ROOT_MODULE: /app/srcs/provision/live/stage/app
      m_ANSIBLE_CONFIG_DIR: /app/srcs/deploy
      m_ANSIBLE_INVENTORY_FILE: inventories/stage/hosts.aws_ec2.yaml
    volumes:
      - ./srcs:/app/srcs
      - ./learn.pem:/app/srcs/deploy/learn.pem
      - ./.passwd:/app/srcs/deploy/.passwd