---
- name: Copy entrypoint file
  ansible.builtin.copy:
    dest: "{{ base_dir }}/mariadb/tools/"
    src: entrypoint.sh

- name: Copy configuration file and Dockerfile
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - dest: "{{ base_dir }}/mariadb/conf/my.cnf"
      src: my.cnf.j2
    - dest: "{{ base_dir }}/mariadb/Dockerfile"
      src: Dockerfile.j2
