---
- name: Copy nginx configuration file and Dockerfile
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - dest: "{{ base_dir }}/nginx/conf/webserver.conf"
      src: webserver.conf.j2
    - dest: "{{ base_dir }}/nginx/Dockerfile"
      src: Dockerfile.j2